### ISSUE TITLE
Car jittering back and forth when frozen

### ISSUE THREAD

**Issue by ndench** [NitrOP7674/FreeplayCheckpoint#12]
Just installed this plugin and I love it! Only issue I'm having is the car will jitter back and forth slightly when it's frozen. I tried turning bakkesmod variance off completely and I have variance for this plugin set to zero as well.

https://user-images.githubusercontent.com/2062388/121806735-754ae200-cc94-11eb-9d46-948a840dea31.mp4

**Comment by NitrOP7674** [comment]
This is just how the plugin works.  There is no way to actually "freeze" time as far as I'm aware, so what we do is rapidly load the same state over and over.  The game keeps running it forward and we keep setting it back.  Aside from some visual glitchiness, it should not cause any problems.

Variance is applied only when resuming the frozen state, to add randomness that forces you to adapt.  The settings for this are also completely separate from the other bakkesmod variance settings.
