### ISSUE TITLE
Replay a shot with controller inputs

### ISSUE THREAD

**Issue by maciekwiso** [NitrOP7674/FreeplayCheckpoint#13]
I have an idea for a similar plugin or extension to checkpoint plugin.
It'd be great to be able to instantly see a replay of your shot (with ability to rewind/go forward) with your controller inputs shown using controller overlay plugin.
That'd help you understand what exactly you did wrong/well.

**Comment by NitrOP7674** [comment]
I've thought about this some, but the plugin doesn't record the user's inputs, just the car/ball position and speed, so I don't think this is feasible.  Sorry!
