### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by johanalkstal** [NitrOP7674/FreeplayCheckpoint#14]
Since Psyonix released their own Freeplay bindings, I haven't been able to make the FreeplayCheckpoint bindings to work, nothing changes when applying the bindings.

Is it still possible to do?

**Comment by NitrOP7674** [comment]
Things are working fine for me.  FWIW I unbound the in-game features (controller config) and use the bakkesmod-provided ones instead.  It could be those interfere with the plugin if you use the same buttons for them.

After that, check your bindings tab in the Bakkesmod console (F2) and make sure the commands you want bound (see the list in the [README](https://github.com/NitrOP7674/FreeplayCheckpoint/blob/main/README.md)) are set up properly.

**Comment by johanalkstal** [comment]
Thanks!
