### ISSUE TITLE
Add cvar boolean (cpt_is_frozen) for other plugins to detect state

### ISSUE THREAD

**Issue by mgavin** [NitrOP7674/FreeplayCheckpoint#21]
I love this plugin and if I were to complete one myself, I would like to check being in the freeze state to stop/pause my own operations.
For instance: I want to do something after a certain amount of time has elapsed, unless freeplay is currently "frozen" as reported by this plugin (I'm thinking when going through checkpoints, cpt_freeze, where the state of freeplay is frozen in place: is_frozen = 1, when play resumes: is_frozen = 0)

I'd make a pull request, but I have to figure out how to make a pull request. Thanks.

**Comment by NitrOP7674** [comment]
Interesting idea.  I already have a boolean for this, it's just not a cvar, so it should be pretty easy to connect the variable to a cvar, I think.

**Comment by NitrOP7674** [comment]
One complication is that "frozen" is now actually a tri-state.  Car & ball frozen, only ball frozen, or neither frozen.  So maybe two booleans, `cpt_car_frozen` and `cpt_ball_frozen`?

**Comment by NitrOP7674** [comment]
Added in a750292!
