### ISSUE TITLE
Feature: have an option to disable the plugin during custom training

### ISSUE THREAD

**Issue by mgavin** [NitrOP7674/FreeplayCheckpoint#25]
I'd like to be able bind a button I use for the plugin in training mode to do something different during being in a custom training pack.

LOVE THE PLUGIN!!!
Thanks

Mayyyyyy or may not look into patching this in later (since I bet it could just be enabled/disabled with a global) depending on stuff.

**Comment by NitrOP7674** [comment]
Seems pretty simple.  It can be a flag just like the other toggleable settings.  Just out of curiosity, what else do you use the button for in custom training?  Or do you have `cpt_freeze` bound to a more "standard" button than right thumb click?

**Comment by NitrOP7674** [comment]
I added a setting for this in the button configuration section.  Feel free to test it out in this [release](https://github.com/NitrOP7674/FreeplayCheckpoint/releases/tag/v1.7.0-pre): https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.7.0-pre/CheckpointPlugin-v1.7.0-pre.zip

There are no other new features so I probably won't push this to bakkesplugins.com at this point.

**Comment by mgavin** [comment]
> Seems pretty simple. It can be a flag just like the other toggleable settings. Just out of curiosity, what else do you use the button for in custom training? Or do you have `cpt_freeze` bound to a more "standard" button than right thumb click?

Since they added the whole select shot / reset shot, I wanted to reuse a general button that I already had for cpt freeze checkpoint. I didn't try the right thumbstick for cpt_freeze, but yeah I would just like to have had the plugin disabled in custom training 😄 . 

Thanks for the update!
