### ISSUE TITLE
Feature: have an option to disable the plugin during workshop maps

### ISSUE THREAD

**Issue by mgavin** [NitrOP7674/FreeplayCheckpoint#26]
Same thing as #25 but for workshop maps, please. 😄

**Comment by NitrOP7674** [comment]
I'm not sure if such a thing is possible, since workshop appears to be very similar to freeplay.  (Note that the "unlimited boost in freeplay" in the basic (non-bakkesmod) settings affects both.)  I can ask on the bakkesmod discord, though.

**Comment by NitrOP7674** [comment]
Looks like even though you are in "freeplay mode" in a workshop map, the "playlist" can be used to determine whether you are in "true freeplay mode" or a workshop map.  Done!

Release: https://github.com/NitrOP7674/FreeplayCheckpoint/releases/tag/v1.7.0-pre2
Download: https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.7.0-pre2/CheckpointPlugin-v1.7.0-pre2.zip
