### ISSUE TITLE
One Checkpoint Makes The Whole Plugin Glitch

### ISSUE THREAD

**Issue by Jodos297** [NitrOP7674/FreeplayCheckpoint#28]
Hey,

Really appreciate the plugin but when I used about 15 checkpoints, I believe, and added the 16th one, which was in the middle of an airdribble where my car is colliding in the ball, which makes these collision sparks and the sound of hitting the ball repeat very quickly which seemed buggy at first.

Soon as I tried to use it, after a brief time the selection of 16 different checkpoints changed to 31 checkpoints. The Biggest Problem though is that it I can only use the 31st Checkpoint, which is about my 7th, i think. Im not quite sure how to reinstall the Plugin and would hope for some help.

Thanks

**Comment by NitrOP7674** [comment]
Can you share your checkpoint file? It should be in your bakkesmod folder under `data/freeplaycheckpoint.data`.

**Comment by NitrOP7674** [comment]
Also, which version of the plugin are you running?

**Comment by Jodos297** [comment]
I attachted my File to the Mail, currently im running version 1.6.0.62.

Sorry for taking so long to respond, I have been extremely distracted the past days.
________________________________
Von: NitrOP7674 ***@***.***>
Gesendet: Samstag, 3. September 2022 00:28
An: NitrOP7674/FreeplayCheckpoint ***@***.***>
Cc: Jodos297 ***@***.***>; Assign ***@***.***>
Betreff: Re: [NitrOP7674/FreeplayCheckpoint] One Checkpoint Makes The Whole Plugin Glitch (Issue #28)


Also, which version of the plugin are you running?

**Comment by Jodos297** [comment]
Nevermind, I just looked further into the problem to find whats wrong, trying to reapply my bindings. I realized the cause of my problem was that for some reason one button was binded to several commands, which was causing the plugin to seem glitchy, even though it was most probably my mistake.

Thank you very much though for trying to help <3
________________________________
Von: NitrOP7674 ***@***.***>
Gesendet: Samstag, 3. September 2022 00:28
An: NitrOP7674/FreeplayCheckpoint ***@***.***>
Cc: Jodos297 ***@***.***>; Assign ***@***.***>
Betreff: Re: [NitrOP7674/FreeplayCheckpoint] One Checkpoint Makes The Whole Plugin Glitch (Issue #28)


Also, which version of the plugin are you running?

**Comment by NitrOP7674** [comment]
Awesome, glad you solved your problem!
