### ISSUE TITLE
BUG: Rewind fails after scoring a goal

### ISSUE THREAD

**Issue by maciekwiso** [NitrOP7674/FreeplayCheckpoint#29]
Sometimes when you push the rewind button right after you scored a goal in freeplay, rewind doesn't work and goal replay is triggered even if scoring is disabled in bakkesmod.

**Comment by NitrOP7674** [comment]
This seems like a regression with the latest RL/bakkesmod patch.  My guess is that setting the ball's position to be inside the goal triggers a goal being scored even with scoring disabled.  I'll check with the bakkesmod people but I'm not sure there's much I'll be able to do about it.

**Comment by NitrOP7674** [comment]
This is more or less what it is.  It seems I found a workaround to this problem, but it makes the plugin work less well when goals are not disabled.

If you don't mind, please try [the latest pre-release version](https://github.com/NitrOP7674/FreeplayCheckpoint/releases/tag/v1.7.0-pre4) and see if it fixes your issue.  (Direct link: https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.7.0-pre4/CheckpointPlugin-v1.7.0-pre4.zip)

**Comment by maciekwiso** [comment]
It fixed the issue but when I press the back button which has binding to cpt_do_checkpoint it doesn't work, it just resets freeplay.
When I manually use cpt_do_checkpoint cmd in bakkes console it works fine

**Comment by NitrOP7674** [comment]
Check your bindings tab and make sure the button somehow isn't bound to
multiple things.

**Comment by maciekwiso** [comment]
This only happens on new version, when I restored to old version of the plugin it worked fine. so something in the new version had to break it

**Comment by NitrOP7674** [comment]
Okay but did you check your bindings? Maybe they're set in a way I'm not
expecting. I've never seen anything like what you are describing, but maybe
I uploaded a buggy version somehow by mistake.

**Comment by maciekwiso** [comment]
Back button has only 1 binding - cpt_checkpoint_do, but in new version it doesn't work.
I added second binding on a different keyboard key for cpt_checkpoint_do and that's working. So there's something wrong with using back button for cpt_checkpoint_do binding

**Comment by NitrOP7674** [comment]
Is that your "reset shot" button in the main game bindings by any chance?

**Comment by maciekwiso** [comment]
Yes, it is. But I didn't change it between the plugin versions, it has always been like that.

**Comment by NitrOP7674** [comment]
This isn't supported, though, and is called out in the readme explicitly.
People have reported similar problems in the past. And it seems with the
latest bug in bakkesmod/RL that this workaround will be needed to prevent
the spurious goal scoring from happening. I'm not sure any other way to
make it work, but this works flawlessly if you don't use reset shot as the
same button as `cpt_do_checkpoint`.

FWIW I am mulling trying an option to make the reset shot button load the
latest checkpoint if it was last loaded recently.

**Comment by NitrOP7674** [comment]
> FWIW I am mulling trying an option to make the reset shot button load the latest checkpoint if it was last loaded recently.

FYI I just added this as an option if you are interested in checking it out.  But it seems using the same button for "reset shot" and `cpt_do_checkpoint` won't really work anymore because of this problem.

https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.7.0-pre5/CheckpointPlugin-v1.7.0-pre5.zip

**Comment by NitrOP7674** [comment]
UPDATE: Please use https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.7.0-pre5-2/CheckpointPlugin-v1.7.0-pre5-2.zip instead; the other version had a bug that caused crashes in it.

**Comment by maciekwiso** [comment]
what exactly the newest version changed? When I set reset shot and cpt_do_checkpoint to back button once again it only reset the shot. When I have them on different buttons it works fine

**Comment by NitrOP7674** [comment]
> what exactly the newest version changed?
See:
> an option to make the reset shot button load the latest checkpoint if it was last loaded recently.

The plugin doesn't support using the same button for reset shot and `cpt_do_checkpoint`. But this can make it so the most common usage of "reset shot" (similar to custom training) interacts nicely with the plugin.
