### ISSUE TITLE
Feature: Saving shots for future replay

### ISSUE THREAD

**Issue by maciekwiso** [NitrOP7674/FreeplayCheckpoint#30]
It'd be very useful if we could save a whole shot like a replay so that we could rewind it in the future to examine it.
It'd help study in detail difficult mechanics.
It'd be especially useful if we could export/import them to be able to share them with other people.
Maybe the best way to do it would be to save the shot replay as a standard RL replay file that we could open like a normal replay.

**Comment by NitrOP7674** [comment]
This isn't really the intent of this plugin, unfortunately.  I've looked into similar things before and the current plugin just isn't up to the task; it would take a pretty significant redesign.
