### ISSUE TITLE
Camera wiggling

### ISSUE THREAD

**Issue by YAKITK** [NitrOP7674/FreeplayCheckpoint#34]
When i reset to the checkpoint the camera is wiggling 

https://user-images.githubusercontent.com/122171922/211163016-621ff17e-48d8-400d-b6de-7acd1af0fb2b.mp4

**Comment by NitrOP7674** [comment]
This is just the way the plugin works.  It can't _actually_ freeze time so it constantly moves everything back to the checkpointed position, which can result in things looking this way.
