### ISSUE TITLE
Always need to reset twice

### ISSUE THREAD

**Issue by schwitzgeburt** [NitrOP7674/FreeplayCheckpoint#36]
Hey,

i have this bug for quite a while now where i always have to reset the shot twice.
On the first reset its always a regular kickoff spawn and then i have to immediately press reset again for it to actually work.

Its very annoying and I can barely use it anymore.
I can also send a short clip if you need one.

**Comment by NitrOP7674** [comment]
Do you have the same button mapped to Reset Shot? If so, map it to something else and it should be fine.

**Comment by schwitzgeburt** [comment]
Yeah but it was working perfectly fine for some time and then it suddenly changed, it was also working when i enabled goal reset till rocket league made their own freeplay settings.
I would like to keep it on the reset button but if you dont have a fix i will change it

**Comment by NitrOP7674** [comment]
There was another breakage that required a change that was incompatible with this button mapping. The change was e43055b to fix #29.

FWIW I added an option in e6bdb21 that lets you use the reset shot button to load the last checkpoint. It's in the latest release.
