### ISSUE TITLE
A request for a new plugin, that will let us modify "Mutator Settings" for Freeplay (If it's actually possible to make something like this)

### ISSUE THREAD

**Issue by herculuis** [NitrOP7674/FreeplayCheckpoint#49]
Hi, thanks for all the things you have done for improving the Freeplay Checkpoint plugin. This plugin single handedly has help me and others improve their mechanics. Now, even though this has nothing to do with FCP, I am requesting for a new plugin that will potentially let us modify "Mutator Setting" during Freeplay. 
I know we have that for private match, but it will be really helpful if we can have that on Freeplay, alongside the d-pad button's command, it will help us train much better compared to let's say private matches. For example, Boomer ball, something I believe Jstn practices quite religiously before tournaments as it helps with precise touches and bounce reads. Having something like that on Freeplay will be gold. Currently, I believe we can only slow down the pace and modify the gravity in Freeplay with Bakkesmod.
I am sorry if you are already busy with your projects. I personally don't know any other developers for Bakkesmod plugins. That's why I thought maybe share this idea for your potential future projects. 
Now, if it's possible at all to make something like this in the first place (as it requires letting us change quite a few things like Boost Strength, Ball Bounces, Ball weight, Ball type, Gravity etc). I am not a game developer or anything like that, so I am not sure if it's actually possible to make something like this for freeplay in the first place. But still, I thought maybe I could reach out to you and maybe ask your opinion.
If it's possible to make something like this, and if you have some time in the future and maybe have interest in making something like this, then this could be a phenomenal addition to Bakkesplugins. 
Happy New Year btw. Good luck with your projects.

**Comment by NitrOP7674** [comment]
Sorry, but I can't help with this.  I made this plugin because it was something I really wanted personally.  I share it with others, because that's easy to do once it exists.  I also have no desire to spend more time on RL plugins, because I'm pessimistic about the direction of the game.  If bakkesmod support is removed in the next 6 months, then I'll have done a bunch of work for nothing.

I'd recommend joining the bakkesmod discord and seeing if you can find out whether something like this is feasible and potentially learning C++ if you can't find someone that would be interested in making it.

Good luck!

**Comment by herculuis** [comment]
No problem. It's understandable. Thankfully I found some console commands in bakkesmod wiki alongside some unreal commands, with the help of these, maybe through modifying the binds.cfg file and binding those commands to a key in keyboard, I can actually play boomer ball in freeplay, I am currently in the process of testing this. I hope it works for me.
And true that the direction the game is going is quite bad and kinda nuts, with so many layoffs, removing trading, questionable RLCS format which is causing some players to retire, no information about UE5, Severe lack of communication with Pros, General players and Content Creators before implementing any significant change, no new gamemode, no nothing. It maybe my bias, but it feels like Epic's main Priority is Fortnite and RL is just a means to an end, the end being Fortnite and milking as much money from RL before it goes down the drain.
In any case, I really appreciate your response and good luck with your future projects.
