### ISSUE TITLE
Automatic return to checkpoint

### ISSUE THREAD

**Issue by maciekwiso** [NitrOP7674/FreeplayCheckpoint#7]
For some training it'd be helpful to be able to just quikly, automatically return to checkpoint every n seconds or on some kind of event. Like when you touched the ball, hit the ground, wall, ceiling, hit hyperspeed.

**Comment by NitrOP7674** [comment]
Thanks for the suggestion.  A couple potential complications I could see are: the UI to configure this would be complex/large with so many different choices of things to reset on, and when the checkpoint is restored, you'll be holding down buttons already, so it will immediately resume, which often will ruin the shot.

For the former point, there are several events I can think that would be most common: goal scored, {ball,car} touches {ground,wall,ceiling}.  This is 7 already, and multiple would want to be active at the same time.

For the latter, it might be feasible to suppress resuming from the checkpoint until after all inputs are released and then one is pressed again.

**Comment by NitrOP7674** [comment]
> For the latter, it might be feasible to suppress resuming from the checkpoint until after all inputs are released and then one is pressed again.

In fact, this should probably be the behavior even when pressing the button to restore a checkpoint.  I've had times where I reset before fully releasing the controls, and the checkpoint resumes instantly, ruining the shot.

**Comment by NitrOP7674** [comment]
This is implemented with 0a5d5543baa257b7e93343efe303b3445ea77389.  I'll make a preview release in a minute if you want to test it out.

**Comment by NitrOP7674** [comment]
If you don't mind testing it out, you can download the preview version here: https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.2.0-pre/CheckpointPlugin-v1.2.0-pre.zip
Just unzip into your bakkesmod directory (`C:\Users\%username%\AppData\Roaming\bakkesmod\bakkesmod`).

I'll submit the new version to bakkesplugins.com after using it for awhile to make sure there are no more bugs, and then it takes a few weeks for them to update it on their site.

**Comment by NitrOP7674** [comment]
Found a small bug; this should fix it: https://github.com/NitrOP7674/FreeplayCheckpoint/releases/tag/v1.20.0-pre2
