### ISSUE TITLE
Cannot set keyboard button as binding

### ISSUE THREAD

**Issue by dariolaplaca** [NitrOP7674/FreeplayCheckpoint#8]
I am a KBM player and I cannot set any keyboard button as a keybind for the plugin

**Comment by NitrOP7674** [comment]
You will need to bind the commands manually in that case.  In the "Bindings" tab of the main bakkesmod window, you can assign actions to buttons.  Assign `cpt_do_checkpoint` (save/load/delete checkpoint), `cpt_freeze`, `cpt_prev_checkpoint`, and `cpt_next_checkpoint` to the keys you want to use for them.
